<img style="float:left" width="70%" src="pics/escudo_COLOR_1L_DCHA.png">
<img style="float:right" width="15%" src="pics/PythonLogo.svg">
<br style="clear:both;">

# Introducción a la programación en Python

<h2 style="display: inline-block; padding: 4mm; padding-left: 2em; background-color: navy; line-height: 1.3em; color: white; border-radius: 10px;">Estructuras de datos básicas</h2>

## Docentes

 - **Pedro Latorre Carmona** (Profesor del curso académico **2022-2023**)
 - César Ignacio García Osorio
 - Juan José Rodríguez Diez
 - José Francisco Diez Pastor
 - Álvar Arnaiz González 

<a id="index"></a>
## Tabla de contenidos del notebook

1. [Repaso de conceptos](#concepts)
2. [Enteros y flotantes &mdash; datos numéricos](#nums)
3. [Valores lógicos y comparaciones](#booleans)
4. [Cadenas &mdash; datos textuales](#strings)
5. [Listas, tuplas y conjuntos &mdash; colecciones de datos](#lists)
6. [Diccionarios &mdash; colecciones indexadas por nombre](#dictionaries)
7. [Vectores, matrices y tensores](#arrays)
8. [Ejercicios y retos](#exercises)


<!--
## Bibliografía
- [Ref1](https://example.com)
- [Ref2](https://example.com)
- [Ref3](https://example.com)
-->


# Repaso de conceptos <a id="concepts"></a><a href="#index"><i class="fa fa-list-alt" aria-hidden="true"></i></a>

Estos son algunos de los conceptos cuyo conocimiento se presupone:
- **Lenguaje de programación**: lenguaje artificial de propósito limitado, que permite expresar cálculos y algoritmos.
- **Programa**: secuencia de instrucciones que permiten la solución de un problema.
- **Variable**: en programación, una variable está formada por un espacio de almacenaje en memoria y un nombre simbólico (un identificador) que está asociado a dicho espacio. Ese espacio contiene una cantidad de información conocida o desconocida, es decir un _valor_. El nombre de la variable es la forma usual de referirse al valor almacenado. Esta separación entre nombre y contenido permite que el nombre sea usado independientemente de la información exacta que representa. 
- **Sentencia**: Instrucción de un lenguaje de programación cuya ejecución consigue un cambio de estado (cambio del valor de una variable, impresión por pantalla, ...).

- **Expresión**: Combinación de valores mediante operadores que da a lugar a un nuevo valor.
- **Condición**: Expresión que devuelve un valor lógico (cierto o falso) y que puede utilizarse para controlar el flujo de ejecución de las sentencias.
- **Sentencia condicional**: Instrucción que tras evaluar una expresión condicional ejecuta o no una secuencia de sentencias, o bien ejecuta un conjunto entre dos conjuntos alternativos.
- **Bucle** o **sentencia iterativa**: Instrucción que permite la ejecución repetitiva de una secuencia de instrucciones. El número de veces en que la secuencia se ejecuta se controla mediante una expresión condicional.
- **Función**: Secuencia de sentencias a las que se le da un nombre para que pueda ser reutilizada en diversas partes del programa. Una función puede devolver un valor y recibir unos valores.
- **Llamar o invocar una función**: Utilizar el nombre de la función para ejecutar sus instrucciones.
- **Parámetro o argumento**: Variable especial a través de la cual una función puede recibir valores a utilizar en sus instrucciones. 
- **Booleano**: Tipo especial de datos que puede tomar uno de dos posibles valores (`True` o `False`).
- **Objeto**: Es una abstracción de algunos lenguajes de programación que permite agrupar en una única entidad los valores y atributos de un elemento de interés. Asimismo, agrupa la funcionalidad que permite modificar y acceder a estos valores. 
- **Clase**: Es una plantilla de construcción de objetos, define los métodos y atributos que tendrá los objetos que se definan por instanciación de la plantilla. 
- **Operador**: Es el carácter (o caracteres) utilizados para representar las acciones de combinación de uno o más valores, por ejemplo `+` para representar la suma, o `**` para representar la potencia.
- **Método**: Es un conjunto de acciones a las que se le asocia un nombre y que se utilizan para recuperar o modificar los valores almacenados en un objeto.

# Enteros y flotantes &mdash; datos numéricos  <a id="nums"></a><a href="#index"><i class="fa fa-list-alt" aria-hidden="true"></i></a>

El tipo más básico que podemos considerar son los datos numéricos. Para prácticamente cualquier tarea necesitamos 
hacer operaciones como contar ocurrencias o acumular magnitudes y valores. 

In [1]:
'''
Los comentarios de varias líneas se introducen
con 3 comillas simples de inicio y otras 3 al final

'''

'\nLos comentarios de varias líneas se introducen\ncon 3 comillas simples de inicio y otras 3 al final\n\n'

## Los tipos numéricos de Python

In [2]:
# Todo lo que sigue al carácter # es un comentario y es ignorado por el interprete Python,
'''
Los comentarios de varias líneas se introducen
con 3 comillas simples de inicio y otras 3 al final

'''

num = 4
print(type(num)) # => <class 'int'>
# La función type devuelve el tipo del valor almacenado en una variable.

num = 3.14
print(type(num)) # => <class 'float'>

<class 'int'>
<class 'float'>


## Operaciones aritméticas

In [3]:
# Suma:            3 + 2
# Resta:           3 - 2
# Multiplicación:  3 * 2
# División:        3 / 2
# División entera: 3 // 2  
# Resto:           3 % 2   
# Potencia:        3 ** 2  
# Raíz cuadrada:   3 ** .5



print(3 / 2)       # Devuelve 1.5 en Python 3, sin embargo, el resultado es 1 en Python 2
print(3 // 2)      # Devuelve 1 tanto en Python 2 como en Python 3

1.5
1


In [148]:
print(13 % 5)      # => 3

# una forma de comprobar si un número es par
print(13 % 2)      # => 1, es impar
print(18 % 2)      # => 0, si el resultado es cero, el número es par

3
1
0


In [5]:
# Precedencias de operadores
# Si no se está seguro usar paréntesis.

print(4 ** 2)      # => 16
print(4 ** .5)     # => 2.0
print(3 * 2 + 1)   # => 7 
print(3 * (2 + 1)) # => 9 

16
2.0
7
9


In [6]:
print((-2) ** 2) # => 4

4


<div class="alert alert-danger">
   <i style="color: #a94442; font-size: larger" class="fa fa-warning" aria-hidden="true"> <b>Conclusión:</b> Cuidado con las precedencias.
</div>


In [7]:
# Operador de actualización y asignación (igual que C y Java)

num = 2
print(num) # => 2
num += 1
print(num) # => 3
num *= 10
print(num) # => 30

2
3
30


## Funciones matemáticas predefinidas

In [8]:
# Valor absoluto y redondeo
print(abs(-3))
print(round(3.86))
print(round(3.86, 1))

3
4
3.9


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Se puede utilizar el comando <kbd>help</kbd> para obtener ayuda sobre funciones.
</div>


In [9]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [10]:
# Otra forma de hacer potencias es la función `pow`
print(pow(-1, .5)) # => (6.123233995736766e-17+1j)
print(pow(-1, .5).real)
print(pow(-1, .5).real + 1 - 1)

(6.123233995736766e-17+1j)
6.123233995736766e-17
0.0


In [11]:
print(max(6,1,8))
print(min(6,1,8))

8
1


En el módulo **math** hay muchas más funciones matemáticas. Lo veremos más adelante

## Coerción de tipos (<span style="color:red;text-transform: uppercase;">opcional</span>)
La <a class="concept" href="http://diccionario.raing.es/es/lema/coerci%C3%B3n-de-tipos">coerción de tipos</a> es la <q cite="http://diccionario.raing.es/es/lema/coerci%C3%B3n-de-tipos">Característica de los lenguajes de programación que permite, implícita o explícitamente, convertir un elemento de un tipo de datos en otro, sin tener en cuenta la comprobación de tipos</q>.

In [12]:
num = 255
print(type(num))
num = str(num)
print(type(num))
num

<class 'int'>
<class 'str'>


'255'

In [13]:
# Sirve para convertir los datos a un tipo que nos permita operar con ellos
# El operador + concatena cadenas, pero no puede sumar una cadena y un número

#cadena = "Estamos en el año "+2018
cadena = "Estamos en el año "+str(2018)
cadena

'Estamos en el año 2018'

In [14]:
print(bin(255))       # => '0b11111111'   número a la cadena correspondiente a su representación binaria
print(bin(170))       # => '0b10101010'   número a la cadena correspondiente a su representación binaria
print(hex(255))       # => '0xff'
print(oct(255))       # => '0x377'

0b11111111
0b10101010
0xff
0o377


In [15]:
print(int('0xff',16)) # => 255
print(int('ff',16))   # => 255
print(int('11',16))   # => 17
print(int('11',2))    # => 3
print(int('11',3))    # => 4

255
255
17
3
4


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Más funciones en:
   <ul>
    <li> <a href="https://docs.python.org/3/library/functions.html">https://docs.python.org/3/library/functions.html</a></li>
   <li> <a href="https://www.programiz.com/python-programming/methods/built-in">https://www.programiz.com/python-programming/methods/built-in</a></li>
    </ul>
</div>


# Comparaciones y valores lógicos  <a id="booleans"></a><a href="#index"><i class="fa fa-list-alt" aria-hidden="true"></i></a>

Comparar valores es fundamental en el control del flujo de ejecución: 
- la ejecución alternativa de sentencias, en las instrucciones condicionales
- la ejecución repetitiva de sentencias, en los bucles

Python tiene las comparaciones típicas de otros lenguajes de programación.

In [16]:
# Igualdad:      3 == 2
# Desigualdad:   3 != 2 (también con: not 3 == 2)
# Mayor que:     3 >  2
# Menor que:     3 <  2
# Mayor o igual: 3 >= 2
# Menor o igual: 3 <= 2
print(3 == 2)
print(3 != 2)
print(3 > 2)

False
True
True


Pero también otras no tan comunes en otros lenguajes.

In [17]:
5 > 4 > 1 # secuencia decreciente

True

In [18]:
-5 < -4 < -1 # secuencia creciente

True

Además las comparaciones pueden combinarse con los operadores lógicos <i class="incode">and</i>, <i class="incode">or</i>, <i class="incode">not</i>. 

In [19]:
val=18
print(val>10 and val % 2 == 0)
print((val % 5 == 1) or (val % 2 == 1))

True
False


In [20]:
print(True and False) 
print(True and True)    # True si los dos son True
print(False or True)    
print(False or False)   # False si los dos son False
print(not True)

False
True
True
False
False


<span class="label label-info"><i class="fa fa-info-circle" aria-hidden="true"></i> Truco</span> Una comparación **`and`** sobre varios valores se puede hacer también con la función **`all`**.

In [150]:
v1 = val>10           # True, 18 es mayor que 10
v2 = val % 2 == 0     # True 18 es par
v3 = False
print(v1)
print(v2)
print(v1 and v2)
print(v1 and v2 and v3)
print(all([v1, v2, v3]))

True
True
True
False
False


<span class="label label-info"><i class="fa fa-info-circle" aria-hidden="true"></i> Truco</span> Una comparación **`or`** sobre varios valores se puede hacer también con la función **`any`**.

In [22]:
v1 = val>10
v2 = val % 2 == 0
v3 = True
print(v1 or v2 or v3)
print(any([v1, v2, v3]))

True
True


In [23]:
print(all([True, True, True, True]))           # combinación con and, todos deben ser True
print(all([True, True, False, True]))
print(any([False, False, False, False]))       # combinación con or, basta si uno es True
print(all([True, True, False, True]))

True
False
False
False


# Cadenas &mdash; datos textuales   <a id="strings"></a><a href="#index"><i class="fa fa-list-alt" aria-hidden="true"></i></a>

Las <i class="concept">cadenas</i> son el tipo de datos utilizado para las secuencias de caracteres, su sintaxis más habitual es la secuencia de caracteres delimitada por comillas simples o dobles.


## Ejemplos básicos

In [153]:
mi_mensaje = "¡Hola mundo!" 
print(mi_mensaje)

¡Hola mundo!


In [151]:
mi_mensaje_largo = """En un lugar
de La Mancha de cuyo
nombre no quiero acordarme vivía ..."""
print(mi_mensaje_largo)
print(len(mi_mensaje_largo)) 

En un lugar
de La Mancha de cuyo
nombre no quiero acordarme vivía ...
69


In [156]:
# Se corresponde con el ejemplo del mensaje de: "¡Hola mundo!"
print(mi_mensaje[0])  # en Python, los índices empiezan en 0
print(mi_mensaje[1])
print(mi_mensaje[11])
#print(mi_mensaje[41]) # ¡OJO! esta daría error, mi_mensaje no es tan largo. Prueba, quitando/borrando "#".

¡
H
!


In [27]:
# Se pueden combinar los dos tipos de comillas por comodidad.

cadena = 'Juan dijo: "Hola"'
print(cadena)

Juan dijo: "Hola"


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> El comando <kbd>help</kbd> también puede utilizarse para obtener ayuda sobre tipos de datos.
</div>


## Rebanado de cadenas (<em class="concept">String slicing</em>) (<span style="color:red;text-transform: uppercase;">opcional</span>)

El <em class="concept">rebanado de cadenas</em> (aplicable también a las listas que se verán <a href="#lists">más adelante</a>) consiste en obtener una subcadena utilizando los índices de inicio y fin de la porción que quiere extraerse; adicionalmente se puede indicar un paso para extraer una subsecuencia. 


El funcionamiento varía según los argumentos:
- `[num:]` Desde num hasta el final
- `[:num]` Desde el principio hasta num
- `[num1:num2]` Desde num1 hasta num2
- `[num1:num2:num3]` Desde num1 hasta num2 a intervalos de num3
- `[::num]` Desde el principio hasta el final a intervalos de num


In [29]:
print(mi_mensaje[4:9]) 
inicio = 9
fin = 60
paso = 3
print(mi_mensaje_largo[inicio:fin:paso])

a mun
adLMc  ynb  iocdm


Se pueden omitir los índices del inicio, del final o ambos.

In [1]:
dígitos = "0123456789"
print(dígitos[0:10])
print(dígitos[0:9])
print(dígitos[0:7])
print(dígitos[:7])

0123456789
012345678
0123456
0123456


In [2]:
print(dígitos[4:])
print(dígitos[4:10])
print(dígitos[:])

456789
456789
0123456789


También se pueden utilizar índices y pasos negativos.

In [3]:
print(dígitos[:-1]) # -1 es la última posición
print(dígitos[3:-2]) # -2 es la penúltima

012345678
34567


In [5]:
# Por que ese resultado? (fíjate también, en particular, en el ejemplo siguiente)
print(dígitos[7:3])  

In [34]:
# Por que ese resultado?

print(dígitos[7:3:-1])
print(dígitos[3:7:-1])

7654



In [163]:
print(dígitos[-2:3:-1])
print(dígitos[-2:-5:-1])

87654
876


## Métodos de cadenas
Los <em class="concept">métodos</em> son porciones de funcionalidad a las que se les da un nombre y se asocia con un objeto. Un <em class="concept">objeto</em> es una entidad de código que agrupa variables (atributos) y
funcionalidad (métodos). Son una forma de obtener valores y hacer operaciones sobre elementos.

In [36]:
print(mi_mensaje.upper())
print(mi_mensaje_largo.count("r")) # cuenta el número de ocurrencias de "r"

¡HOLA MUNDO!
5


In [37]:
print(mi_mensaje_largo.find("mancha"))
print(mi_mensaje_largo.find("Mancha"))

-1
18


In [166]:
mi_nuevo_mensaje = mi_mensaje.replace("Hola", "Buenos días")
print(mi_nuevo_mensaje)

¡Buenos días mundo!


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Se puede utilizar el comando <kbd>dir</kbd> para obtener los métodos asociados a un objeto.
</div>


## Formateado de cadenas (<span style="color:red;text-transform: uppercase;">opcional</span>)

El formateo de cadenas es la manera más moderna y elegante de combinar cadenas con los valores de otras variables.

La forma menos elegante es simplemente concatenar cadenas con el operador `+`, si es necesario podemos hacer un cambio de tipo con `str()`

In [169]:
print("Buenos días" "Pedro Latorre")
saludo = "Buenos días,"
nombre = "Pedro Latorre"
mi_mensaje = saludo + nombre
print(mi_mensaje) # Ojo con los espacios cuando se concatenan cadenas

Buenos díasPedro Latorre
Buenos días,Pedro Latorre


In [172]:
mi_mensaje = saludo + " " + nombre + " ¿Has dormido bien?"
print(mi_mensaje)

Buenos días, Pedro Latorre ¿Has dormido bien?


Con el formateo de cadenas sustituimos las llaves por los argumentos del `format`.
- La sustitución puede ser por posición (el valor n-esimo en el hueco n-esimo)
- La sustitución puede ser por nombre.
- La sustitución puede ser por posición, pero indicando explicitamente la posición del valor que se quiere incluir.

In [42]:
mi_mensaje = "{} {}, ¿has dormido bien?".format(saludo, nombre)
print(mi_mensaje)
mi_mensaje = "{saludo} {nombre}, ¿has dormido bien?".format(saludo=saludo, nombre=nombre)
print(mi_mensaje)

Buenos días César, ¿has dormido bien?
Buenos días César, ¿has dormido bien?


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Más información sobre el formateado avanzado en: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior
</div>


# Listas, tuplas y conjuntos &mdash; colecciones de datos   <a id="lists"></a><a href="#index"><i class="fa fa-list-alt" aria-hidden="true"></i></a>

* [Listas](#listas)
    - [Rebanado de listas](#listsSlicing)
    - [Otras operaciones con listas](#otherOpsOnList)
    - [Listas por comprensión](#listsComprehension)
    - [Copia de listas](#listsCopy)
* [Tuplas](#tuples)
* [Conjuntos](#sets)
    - [Operaciones sobre conjuntos](#setsOperators)
    - [Conjuntos vacíos](#emptySets)

## Listas <a id="listas"></a>

Una <i class="concept">lista</i> es una colección **mutable** de elementos (no necesariamente del mismo tipo) en las que el orden es relevante. Se delimitan con corchetes y sus elementos se separan por comas.

In [173]:
ríos = ["Nilo", "Arlanza", "Cerezo", "Pico", "Vena"]
print(ríos)
print(len(ríos))

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena']
5


Se puede acceder a los elementos de una lista utilizando un índice (<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span> Hay que tener en cuenta que el índice del primer elemento es 0, no 1 como en otros lenguajes de programación).

In [51]:
print(ríos[1]) # => 'Arlanza', dado que los índices empiezan en 0
print(ríos[len(ríos)-1]) # Para obtener el último de los elementos
print(ríos[-1])

Arlanza
Vena
Vena


<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span> Utilizar un índice mayor o igual que la longitud de la lista dará un error. 

In [52]:
#print(ríos[11]) # => Error! index out of range

Se pueden añadir elementos al final de una lista con el método `append`.

In [174]:
ríos.append("Duero")
print(ríos)

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Duero']


Se pueden insertar elementos en posiciones arbitrarias con el método `insert`.

In [54]:
antes_de_esta_posición = 0
print(ríos)
ríos.insert(antes_de_esta_posición, "Colorado")
print(ríos)

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Duero']
['Colorado', 'Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Duero']


In [55]:
antes_de_esta_posición = 3
print(ríos)
ríos.insert(antes_de_esta_posición, "Danubio")
print(ríos)

['Colorado', 'Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Duero']
['Colorado', 'Nilo', 'Arlanza', 'Danubio', 'Cerezo', 'Pico', 'Vena', 'Duero']


<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span> Si lo que se inserta es a su vez una lista, la lista insertada aparece como nuevo elemento (recuerda, los elementos de una lista pueden ser de tipos arbitrarios, incluidas las listas).

In [56]:
ríos = ["Nilo", "Arlanza", "Cerezo", "Pico", "Vena" ]
más_ríos = ["Danubio", "Ebro" ]
print(ríos)
ríos.insert(2, más_ríos)
print(ríos)

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena']
['Nilo', 'Arlanza', ['Danubio', 'Ebro'], 'Cerezo', 'Pico', 'Vena']


In [57]:
# El operador + concatena listas
ríos = ["Nilo", "Arlanza", "Cerezo", "Pico", "Vena" ]
más_ríos = ["Oca", "Danubio", "Ebro", "Guadalmedina", "Eo" ]
ríos += más_ríos
print(ríos)

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Oca', 'Danubio', 'Ebro', 'Guadalmedina', 'Eo']


<div class="alert alert-danger">
   <i style="color: #a94442; font-size: larger" class="fa fa-warning" aria-hidden="true"> IMPORTANTE: El operador <kbd>+</kbd> concatena listas, el método <kbd>.insert</kbd> inserta un nuevo elemento, si éste es una lista, la lista aparece dentro de la otra lista.
</div>

Si tenemos una lista de números, podemos usar sus elementos (función `sum`), o encontrar el máximo (función `max`), o encontrar el mínimo (función `min`). <span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span>
Las funciones `max` y `min` funcionan tanto si se les pasa un número variables de argumentos, como si se les pasa una colección, pero la función `sum` sólo funciona cuando se le pasa como único argumento una colección.

In [58]:
nums = [5, 7, 9, 2]
print(sum(nums))
print(max(nums))
print(min(nums))

23
9
2


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Podemos comprobar si un elemento está dentro de una lista (o dentro de cualquier colección) utilizando el operador `in`.
</div>


In [59]:
print("Cerezo" in ríos)
print("Bernesga" in ríos)

True
False


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Ya hemos visto por tanto ejemplos de los tres conceptos <i class="concept">método</i>, <i class="concept">función</i> y <i class="concept">operador</i>.
</div>


### Rebanado de listas <a id="listsSlicing"></a>
El rebanado de listas (aplicable también a cadenas) consiste en obtener una sublista utilizando los índices de inicio y fin de los elementos que quiere extraerse; adicionalmente se puede indicar un paso para extraer elementos no consecutivos.

In [60]:
# La misma idea que con las cadenas de texto

una_lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print(una_lista[3:8])
print(una_lista[1:9:2])

[3, 4, 5, 6, 7]
[1, 3, 5, 7]


Se pueden omitir los índices del inicio, del final o ambos.

In [61]:
print(una_lista[6:])
print(una_lista[:4])
print(una_lista[:]) # Devuelve la lista entera, se puede usar para hacer copias.
print(una_lista[::3]) 

[6, 7, 8, 9]
[0, 1, 2, 3]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 3, 6, 9]


También se pueden utilizar índices y pasos negativos.

In [62]:
print(una_lista[-4:])
print(una_lista[-7:-2])
print(una_lista[3:-2])
print(una_lista[-7:8])
print(una_lista[:-6])
print(una_lista[2:-1:2])
print(una_lista[2:-1:-1]) # => []
print(una_lista[-1:2:-1]) 
print(una_lista[::-1]) 

[6, 7, 8, 9]
[3, 4, 5, 6, 7]
[3, 4, 5, 6, 7]
[3, 4, 5, 6, 7]
[0, 1, 2, 3]
[2, 4, 6, 8]
[]
[9, 8, 7, 6, 5, 4, 3]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


### Otras operaciones con listas (<span style="color:red;text-transform: uppercase;">opcional</span>) <a id="otherOpsOnList"></a> 

In [63]:
print(ríos)
ríos.reverse()
print(ríos)

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Oca', 'Danubio', 'Ebro', 'Guadalmedina', 'Eo']
['Eo', 'Guadalmedina', 'Ebro', 'Danubio', 'Oca', 'Vena', 'Pico', 'Cerezo', 'Arlanza', 'Nilo']


In [64]:
print(ríos[::-1])

['Nilo', 'Arlanza', 'Cerezo', 'Pico', 'Vena', 'Oca', 'Danubio', 'Ebro', 'Guadalmedina', 'Eo']


In [65]:
print(ríos)
res = sorted(ríos)
print(res)
print(ríos) # La lista original no se ve afectada

['Eo', 'Guadalmedina', 'Ebro', 'Danubio', 'Oca', 'Vena', 'Pico', 'Cerezo', 'Arlanza', 'Nilo']
['Arlanza', 'Cerezo', 'Danubio', 'Ebro', 'Eo', 'Guadalmedina', 'Nilo', 'Oca', 'Pico', 'Vena']
['Eo', 'Guadalmedina', 'Ebro', 'Danubio', 'Oca', 'Vena', 'Pico', 'Cerezo', 'Arlanza', 'Nilo']


In [66]:
res = ríos.sort() 
print(ríos) # Se ordena la lista original 
print(res)  # El valor devuelto es None

['Arlanza', 'Cerezo', 'Danubio', 'Ebro', 'Eo', 'Guadalmedina', 'Nilo', 'Oca', 'Pico', 'Vena']
None


In [67]:
ríos.sort(reverse=True)
print(ríos)
print(sorted(ríos, key=len))

['Vena', 'Pico', 'Oca', 'Nilo', 'Guadalmedina', 'Eo', 'Ebro', 'Danubio', 'Cerezo', 'Arlanza']
['Eo', 'Oca', 'Vena', 'Pico', 'Nilo', 'Ebro', 'Cerezo', 'Danubio', 'Arlanza', 'Guadalmedina']


In [69]:
ríos = ['Danubio', 'Ebro', 'Oca', 'Vena', 'Cerezo', 'Pico', 'Nilo', 'Eo', 'Arlanza', 'Guadalmedina']
print(ríos)
ríos.remove("Pico")
print(ríos)

['Danubio', 'Ebro', 'Oca', 'Vena', 'Cerezo', 'Pico', 'Nilo', 'Eo', 'Arlanza', 'Guadalmedina']
['Danubio', 'Ebro', 'Oca', 'Vena', 'Cerezo', 'Nilo', 'Eo', 'Arlanza', 'Guadalmedina']


In [70]:
print(ríos)
ríos.pop()
print(ríos)

['Danubio', 'Ebro', 'Oca', 'Vena', 'Cerezo', 'Nilo', 'Eo', 'Arlanza', 'Guadalmedina']
['Danubio', 'Ebro', 'Oca', 'Vena', 'Cerezo', 'Nilo', 'Eo', 'Arlanza']


In [71]:
print(ríos)
un_río = ríos.pop()
print(ríos)
print(un_río)

['Danubio', 'Ebro', 'Oca', 'Vena', 'Cerezo', 'Nilo', 'Eo', 'Arlanza']
['Danubio', 'Ebro', 'Oca', 'Vena', 'Cerezo', 'Nilo', 'Eo']
Arlanza


In [72]:
#[].pop() # => pop de lista vacía, SyntaxError

In [73]:
print(ríos.index("Cerezo"))

4


### Listas por comprensión (<span style="color:red;text-transform: uppercase;">opcional</span>) <a id="listsComprehension"></a> 

<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> La definición de listas por compresión es una de las características más potentes de Python. Entender su funcionamiento puede ayudarnos a simplificar enormemente nuestro código. 
</div>


In [175]:
nums = [5, 2, 7, 8, 9, 4]
print([ n*10 for n in nums ])
print([ n*10 for n in nums if n%2 ]) # Si el resto da "cero", es lo mismo que considerar la opción "false".
print([ n*10 for n in nums if not n%2 ])

[50, 20, 70, 80, 90, 40]
[50, 70, 90]
[20, 80, 40]


In [75]:
ríos = ["Nilo", "Arlanza", "Cerezo", "Pico", "Vena" ]
print([ (n, r) for n, r in enumerate(sorted(ríos)) ])
print([ (n, r) for n, r in enumerate(sorted(ríos), start=1) ])
print('\n'.join([ str(n) + '. ' + r for n, r in enumerate(sorted(ríos), start=1) ]))

"Hola que tal estás".split(' ')

[(0, 'Arlanza'), (1, 'Cerezo'), (2, 'Nilo'), (3, 'Pico'), (4, 'Vena')]
[(1, 'Arlanza'), (2, 'Cerezo'), (3, 'Nilo'), (4, 'Pico'), (5, 'Vena')]
1. Arlanza
2. Cerezo
3. Nilo
4. Pico
5. Vena


['Hola', 'que', 'tal', 'estás']

<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> <kbd>enumerate</kbd> se aplica a una lista (en general a un objeto iterable) para poder obtener una secuencia de pares constituidos por los elementos de la lista junto con el orden de éstos.
</div>


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Un <i class="concept">iterable</i> es un objeto que devuelve un iterador, un <i class="concept">iterador</i> es un objeto que tiene un método <kbd>&lowbar;&lowbar;next&lowbar;&lowbar;</kbd> que con cada invocación devuelve un elemento del iterable en secuencia.
</div>


In [76]:
help(enumerate)

Help on class enumerate in module builtins:

class enumerate(object)
 |  enumerate(iterable, start=0)
 |  
 |  Return an enumerate object.
 |  
 |    iterable
 |      an object supporting iteration
 |  
 |  The enumerate object yields pairs containing a count (from start, which
 |  defaults to zero) and a value yielded by the iterable argument.
 |  
 |  enumerate is useful for obtaining an indexed list:
 |      (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __next__(self, /)
 |      Implement next(self).
 |  
 |  __reduce__(...)
 |      Return state information for pickling.
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.



### La copia de listas <a id="listsCopy"></a>  (<span style="color:red;text-transform: uppercase;">OJO</span>) 

Veamos lo que ocurre con la copia de listas.


Al asignar una lista a otra variable no se hace una copia, sino que la nueva variable apunta a la misma posición de memoria.

**¡OJO!**: Si modificamos la lista, se modifica el valor de la nueva variable, puesto que apunta a la misma posición de memoria.

In [77]:
lista1 = [1,2]
lista2 = lista1

print(lista1)
print(lista2)
print(lista2[1])
lista1[0] = 10
print(lista1)
print(lista2)

[1, 2]
[1, 2]
2
[10, 2]
[10, 2]


<span class="label label-warning"><i class="fa fa-warning" aria-hidden="true"></i> ¡Cuidado!</span> La copia de listas es ligeramente más complicada que los ejemplos que hemos visto. 

In [177]:
# Aquí, lo que vemos es que aunque modifiquemos algún elemento de "lista1", "lista2" no se ve modificado.

lista1 = [1,2]
lista2 = lista1[:]

print(lista1)
print(lista2)
print(lista2[1])
lista1[0] = 10
print(lista1)
print(lista2)

[1, 2]
[1, 2]
2
[10, 2]
[1, 2]


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Para entender mejor lo que está ocurriendo, probar los ejemplos anteriores en el [Python Tutor](http://www.pythontutor.com/).
</div>


In [79]:
%%HTML
<style>.output_wrapper,.output{height:auto !important;max-height:360px;}.output_scroll{box-shadow:none !important;webkit-box-shadow:none !important;}</style>
<iframe width="800" height="350" frameborder="0" src="http://pythontutor.com/iframe-embed.html#code=lista1%20%3D%20%5B'Vena',%20%5B'Ebro'%5D%5D%0Alista2%20%3D%20lista1%5B%3A%5D%0Aprint%28lista1%29%0Aprint%28lista2%29%0Alista2%5B1%5D%5B0%5D%20%3D%20'El%20rio%20Ebro'%0Alista1%5B0%5D%20%3D%20'Pico'%0Aprint%28lista1%29%0Aprint%28lista2%29&codeDivHeight=400&codeDivWidth=350&cumulative=false&curInstr=8&heapPrimitives=false&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false">Hay problemas de conexión con <a href="https://goo.gl/kLfJsk">el ejemplo en Python tutor</a></iframe>

<hr style="background-color: navy; border-top: 1px solid navy;"/>
Otro ejemplo más que ilustra la diferencia entre la copia superficial (<a href="https://en.wikipedia.org/wiki/Object_copying#Shallow_copy" class="concept">shallow copy</a>) y la copia profunda (<a href="https://en.wikipedia.org/wiki/Object_copying#Deep_copy" class="concept">deep copy</a>).

In [80]:
%%HTML
<style>.output_wrapper,.output{height:auto !important;max-height:1000px;}.output_scroll{box-shadow:none !important;webkit-box-shadow:none !important;}</style>
<iframe width="800" height="720" frameborder="0" src="http://pythontutor.com/iframe-embed.html#code=l0%20%3D%20%5B1,%202%5D%0Al1%20%3D%20%5B%5B1,'a'%5D,%5B2,'b'%5D%5D%0Al2%20%3D%20l1%0Al3%20%3D%20l1%5B%3A%5D%0Aprint%28f%22l1%3A%20%7Bl1%7D,%20l3%3A%20%7Bl3%7D%5Cnl2%3A%20%7Bl2%7D%5Cn%22%29%0Al1%5B0%5D%3D1%0Aprint%28f%22l1%3A%20%7Bl1%7D,%20l3%3A%20%7Bl3%7D%5Cnl2%3A%20%7Bl2%7D%5Cn%22%29%0Al1%5B1%5D%5B0%5D%3D666%0Aprint%28f%22l1%3A%20%7Bl1%7D,%20l3%3A%20%7Bl3%7D%5Cnl2%3A%20%7Bl2%7D%5Cn%22%29%0Afrom%20copy%20import%20deepcopy%0Al4%20%3D%20deepcopy%28l3%29&codeDivHeight=400&codeDivWidth=350&cumulative=false&curInstr=11&heapPrimitives=false&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false">Hay problemas de conexión con <a href="https://goo.gl/VKZi5K">el ejemplo en Python tutor</a></iframe>

## Tuplas <a id="tuples"></a>

Las <i class="concept">tuplas</i> son como listas, pero **no se pueden modificar**, es decir, una vez que se crean, sus valores no pueden cambiarse. Las tuplas pueden usarse como claves de diccionarios (que se verán <a href="#dictionaries">más adelante</a>) o como elementos de conjuntos, en cambio las listas no.

Una de las ventajas de las tuplas es que son mucho más rápidas.

In [81]:
%%timeit
lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

88.1 ns ± 20 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [82]:
%%timeit
tupla = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

13.5 ns ± 0.196 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span> la evaluación de la siguiente celda dará error, dado que las tuplas, una vez creadas, no pueden modificarse.

In [83]:
#tupla[0] = 'Pico' # => TypeError: 'tuple' object does not support item assignment

Más ejemplos de cosas que pueden hacerse con tuplas:

In [84]:
a, b = 1, 2     # inicialización simultánea de varias variables.
print(a,b)
a, b = b, a     # intercambio de valores de variables
print(a,b)
a, _ = 12, 13   # recuperación de valores de una tupla, ignorando los que no interesan
print(a)

1 2
2 1
12


<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span> la evaluación de la siguiente celda dará error, dado que a la izquierda hay menos variables que valores a la derecha.

In [85]:
#a, b = 1, 2, 3 # => ValueError: too many values to unpack (expected 2)

<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span> la evaluación de la siguiente celda dará error, dado que a la izquierda hay más variables que valores a la derecha.

In [86]:
#a, b, c = 1, 2 # => ValueError: not enough values to unpack (expected 3, got 2)

## Conjuntos <a id="sets"></a>
Los <i class="concept">conjuntos</i> son colecciones de objetos en las que el orden no es relevante y donde no se permiten duplicados.

Se pueden modificar (aunque existe una versión no modificable, los 
 <a href="https://docs.python.org/3/library/stdtypes.html#frozenset">frozenset</a>). 

La comprobación de que un elemento pertenece a un conjunto (operador `in`) es más eficiente y rápida que la comprobación 
de que un elemento pertenece a una lista.


In [179]:
# ¡OJO!: Fíjate que el orden no tiene por qué coincidir con el utilizado/considerado en/durante la definición
ríos = { "Nilo", "Arlanza", "Cerezo", "Pico", "Vena", "Nilo", "Cerezo" }
print(ríos)

{'Arlanza', 'Vena', 'Pico', 'Cerezo', 'Nilo'}


### Operaciones con conjuntos <a id="setsOperators"></a>
Con el tipo de datos `set` se pueden hacer las mismas operaciones que con los conjuntos matemáticos: 
- Intersección, 
- Diferencia, 
- Unión, 
- Comprobación de pertenencia, 
- ...

In [88]:
unos_ríos = { "Nilo", "Arlanza", "Cerezo", "Pico" }
otros_ríos = { "Nilo", "Danubio", "Cerezo" }
otros_ríos.add("Bernesga")
print(otros_ríos)
print(unos_ríos.intersection(otros_ríos))
print(unos_ríos & otros_ríos)

{'Cerezo', 'Nilo', 'Bernesga', 'Danubio'}
{'Nilo', 'Cerezo'}
{'Nilo', 'Cerezo'}


In [89]:
print(unos_ríos.difference(otros_ríos))
print(unos_ríos.union(otros_ríos))
print(unos_ríos | otros_ríos)

{'Arlanza', 'Pico'}
{'Arlanza', 'Danubio', 'Pico', 'Cerezo', 'Nilo', 'Bernesga'}
{'Arlanza', 'Danubio', 'Pico', 'Cerezo', 'Nilo', 'Bernesga'}


In [90]:
print({1,2,3,4}.issubset({1,2,3,4,5}))
print({1,2,3,4} < {1,2,3,4,5})

True
True


In [91]:
print({1,2,3,4,5}.issuperset({1,2,3,4}))
print({1,2,3,4,5} > {1,2,3,4})



True
True


In [92]:
print(unos_ríos.symmetric_difference(otros_ríos)) # pertenece a uno, a otro, pero no a los dos
print(unos_ríos ^ otros_ríos)

{'Arlanza', 'Danubio', 'Pico', 'Bernesga'}
{'Arlanza', 'Danubio', 'Pico', 'Bernesga'}


In [93]:
# True si no tienen nada en común
print(unos_ríos.isdisjoint(otros_ríos))

False


### Conjuntos vacíos <a id="emptySets"></a>

In [94]:
lista_vacía = []
print(type(lista_vacía))
tupla_vacía = ()
print(type(tupla_vacía))

<class 'list'>
<class 'tuple'>


In [95]:
# Pero esto no pasa con conjuntos
conjunto_vacío = {} # => {} es en realidad para diccionarios
print(type(conjunto_vacío))

<class 'dict'>


In [96]:
conjunto_vacío = set() 
print(type(conjunto_vacío))

<class 'set'>


In [97]:
# También se pueden usar los constructores para listas y tuplas
lista_vacía = list()
tupla_vacía = tuple()
print(type(lista_vacía))
print(type(tupla_vacía))

<class 'list'>
<class 'tuple'>


# Diccionarios &mdash; colecciones indexadas por nombre   <a id="dictionaries"></a><a href="#index"><i class="fa fa-list-alt" aria-hidden="true"></i></a>

Los <i class="concept">diccionarios</i> son estructuras de datos en las que los elementos constituyentes se pueden recuperar utilizando claves que no tienen por qué ser valores numéricos, como ocurre con las listas y las tuplas. **Las claves de acceso pueden ser cualquier valor _inmutable_**, aunque lo más habitual es usar cadenas.

Como en los conjuntos, **el orden no es relevante** en los diccionarios.

Se delimitan con llaves (como los conjuntos), sus elementos se separan por comas (como en las listas y los conjuntos), pero (**IMPORTANTE**) éstos están conformados por pares de <i class="concept">clave</i> y <i class="concept">valor</i> (la clave separada del valor por dos puntos `:`). Los valores pueden ser de tipos arbitrarios y distintos para cada par.

In [98]:
un_río = { 'nombre': 'Nilo', 'longitud': 6853, # km
    'ciudades': ['El Cairo', 'Jartum', 'Jinja', 'Yuba'] }

El acceso a los elementos se hace con la misma sintaxis que en las listas, pero ahora, en vez de un índice, se utiliza el valor de la clave del elemento que quiere recuperarse o modificarse.

In [99]:
un_río['nombre']

'Nilo'

In [100]:
un_río['ciudades']

['El Cairo', 'Jartum', 'Jinja', 'Yuba']

<span class="label label-danger"><i class="fa fa-bomb" aria-hidden="true"></i> ¡Cuidado!</span> Si se utiliza una clave de acceso no existente en el diccionario, se genera un error..

In [101]:
#un_río['caudal'] # => KeyError: 'caudal' 

<span class="label label-info"><i class="fa fa-info-circle" aria-hidden="true"></i> Truco</span> Si quieres evitar el error de utilizar una clave inexistente, puedes utilizar el método `get` cuyo segundo valor será devuelto en caso de que la clave no exista en el diccionario.

In [102]:
un_río.get('caudal','eso no lo sé')

'eso no lo sé'

In [103]:
print(f"su caudal es: {un_río.get('caudal')}")
print(f"su caudal es: {un_río.get('caudal', 'eso no lo sé')}")

su caudal es: None
su caudal es: eso no lo sé


La modificación de los valores se hace como en la lista, pero usando la clave como valor de acceso.

In [104]:
un_río['caudal'] = 2.830 # m^3/s , valor inventado. el Nilo tiene un caudal mucho mayor
print(un_río)

{'nombre': 'Nilo', 'longitud': 6853, 'ciudades': ['El Cairo', 'Jartum', 'Jinja', 'Yuba'], 'caudal': 2.83}


Se pueden modificar varios elementos usando el método `update`.

In [105]:
un_río.update({'caudal': 2830, 'afluentes': ['Nilo blanco', 'Nilo azul',
    'Ora', 'Gumara', 'Dinder', 'Sobat', '...']})
print(un_río)

{'nombre': 'Nilo', 'longitud': 6853, 'ciudades': ['El Cairo', 'Jartum', 'Jinja', 'Yuba'], 'caudal': 2830, 'afluentes': ['Nilo blanco', 'Nilo azul', 'Ora', 'Gumara', 'Dinder', 'Sobat', '...']}


Se pueden eliminar un elemento usando el **operador** `del`.

In [106]:
del un_río['afluentes']
print(un_río)

{'nombre': 'Nilo', 'longitud': 6853, 'ciudades': ['El Cairo', 'Jartum', 'Jinja', 'Yuba'], 'caudal': 2830}


### Otras operaciones con diccionarios 

In [107]:
# obtiene el valor y elimina la clave
ciudades = un_río.pop('ciudades')
print(ciudades)

# ya no sale la clave ciudades
print(un_río)


['El Cairo', 'Jartum', 'Jinja', 'Yuba']
{'nombre': 'Nilo', 'longitud': 6853, 'caudal': 2830}


In [108]:
# len cuenta el número de claves, no el número total de elementos
print(f"len(un_río): {len(un_río)}")

len(un_río): 3


In [109]:
print(f"un_río.keys(): {un_río.keys()}")           # Devuelve las claves
print(f"un_río.values(): {un_río.values()}")       # Devuelve los valores
print(f"un_río.items(): {un_río.items()}")         # Devuelve todos los pares (clave,valor)

un_río.keys(): dict_keys(['nombre', 'longitud', 'caudal'])
un_río.values(): dict_values(['Nilo', 6853, 2830])
un_río.items(): dict_items([('nombre', 'Nilo'), ('longitud', 6853), ('caudal', 2830)])


## Comparaciones de distintas colecciones

In [112]:
lista1 = [1,2,3]
lista2 = lista1[:]
lista3 = lista1
lista4 = [3,1,2]

# El == compara valores
print(lista1 == lista2)      #tienen los mismos valores
print(lista1 == lista3)      #tienen los mismos valores

# El operador is compara referencias
print(lista1 is lista2)       #no es la misma referencia
print(lista1 is lista3)       #es la misma referencia

True
True
False
True


In [113]:
tupla1 = (1,2,3)
set1 = {1,2,3}
set2 = {3,1,2}

print(lista1 == tupla1)        # Tienen los mismos valores, pero no es el mismo tipo
print(lista1 == list(tupla1))  # ahora mismos valores y mismo tipo
 
print(set1 == set2)            # igual, porque no importa el orden
 
print(lista1 == lista4)       # no son iguales, porque importa el orden
print(set(lista1) == set(lista4))  # ahora si son iguales, porque no importa el orden

False
True
True
False
True


# Vectores, matrices y tensores   (<span style="color:red;text-transform: uppercase;">opcional</span>)  

En Python no existen tipos específicos para los <i class="concept">vectores</i>, las <i class="concept">matrices</i> y los <i class="concept">tensores</i>. Los vectores son fácilmente representables como listas, las matrices podrían representarse como listas de listas, y del mismo modo los tensores de más dimensiones podrían representarse como listas de tensores de dimensiones menores. Pero el acceso a los elementos usando esta representación se hace un poco engorroso. Además tendríamos que programar las operaciones para manipular estos objetos: sumas, productos, traspuestas, inversas, ...

In [180]:
# Un ejemplo de vectores
v1 = [7, 9, 6]
v2 = [-1, -3, 0]
# La suma de vectores
v_suma = [v1[0]+v2[0], v1[1]+v2[1], v1[2]+v2[2]] # MÉTODO AVANZADO: v_suma = [e1+e2 for e1, e2 in zip(v1, v2)]
print(f"v_suma => {v_suma}")

# Un ejemplo de matriz
M = [[2, 3], [4, 5]]
print(f"M => {M}")
# Accediendo a un elemento de M
print(f"M[0][1] => {M[0][1]}")

# Un ejemplo de tensor
M1 = [[2, 3, 1], [4, 5, -2]]
M2 = [[3, -1, 69], [0, 1, -1]]
T = [M1, M2]
print(f"T => {T}")
# Accediendo a un elemento de T. En el caso de 3D, el primer índice se corresponde con el de la tercera dimensión. 
# En el caso siguiente, estaría indicando la segunda matriz.
print(f"T[1][0][2] => {T[1][0][2]}")

v_suma => [6, 6, 6]
M => [[2, 3], [4, 5]]
M[0][1] => 3
T => [[[2, 3, 1], [4, 5, -2]], [[3, -1, 69], [0, 1, -1]]]
T[1][0][2] => 69


Para facilitar un poco la utilización de este tipo de objetos existe la biblioteca [Numpy](http://www.numpy.org/).

Numpy ofrece el tipo `array` que se puede utilizar para representar tensores de dimensiones arbitrarias (también tiene el tipo `matrix` para los tensores bi-dimensionales, _aunque su uso de desaconseja_).

Para poder utilizar estos tipos, lo único que tenemos que hacer es importar el paquete `numpy`. Además, la tradición establecida es renombrarlo a `np` para ahorrarnos pulsaciones de teclado.

In [7]:
import numpy as np

Ahora podemos utilizar toda la funcionalidad que proporcionan `numpy`, lo que nos permitirá manipular tensores como si fueran tipos básicos.

In [116]:
# Un ejemplo de vectores
v1 = np.array([7, 9, 6])
v2 = np.array([-1, -3, 0])
# La suma de vectores
v_suma = v1 + v2
print(f"v_suma => {v_suma}")

v_suma => [6 6 6]


In [117]:
# Un ejemplo de matriz
M = np.array([[2, 3], [4, 5]])
print(f"M =>\n{M}")
# Accediendo a un elemento de M
print(f"M[0, 1] => {M[0, 1]}")

M =>
[[2 3]
 [4 5]]
M[0, 1] => 3


In [14]:
# Un ejemplo de tensor
t1 = [[2, 3, 1], [4, 5, -2]]
t2 = [[3, -1, 69], [0, 1, -1]]
T = np.array([t1, t2])
print(f"T =>\n {T}")
# Accediendo a un elemento de T
print(f"T[1, 0, 1] => {T[1, 0, 1]}")

T =>
 [[[ 2  3  1]
  [ 4  5 -2]]

 [[ 3 -1 69]
  [ 0  1 -1]]]
T[1, 0, 1] => -1


<span class="label label-info"><i class="fa fa-info-circle" aria-hidden="true"></i> Truco</span> Un importante concepto en Numpy es el de [<i class="concept">broadcasting</i>](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html), básicamente consiste en que cuando se combina con un operador dos arrays, el tamaño del menor se transforma para hacerlo compatible con el del mayor.

In [119]:
M = np.array([[-2, 3], [4, -5]])
v = np.array([[2, 3]])
print(f"M + 10 =>\n {M + 10}")
print(f"M * 5 =>\n {M * 5}")
print(f"M - v =>\n {M - v}")

M + 10 =>
 [[ 8 13]
 [14  5]]
M * 5 =>
 [[-10  15]
 [ 20 -25]]
M - v =>
 [[-4  0]
 [ 2 -8]]


In [120]:
print(f"M =>\n {M}")
print(f"M == 2 =>\n {M == 2}")
print(f"M > 2 =>\n {M > 2}")
print(f"M == v =>\n {M == v}")

M =>
 [[-2  3]
 [ 4 -5]]
M == 2 =>
 [[False False]
 [False False]]
M > 2 =>
 [[False  True]
 [ True False]]
M == v =>
 [[False  True]
 [False False]]


<span class="label label-info"><i class="fa fa-info-circle" aria-hidden="true"></i> Truco</span> Cuando se trabaja con arrays, los equivalentes a `sum`, `all` y `any`, que se usaban para colecciones, son `np.sum`, `np.all` y `np.any`.

In [121]:
print(f"M =>\n {M}")
print(f"M > -10 =>\n {M > -10}")
print(f"np.all(M > -10) => {np.all(M > -10)}")
print(f"np.sum(M) =>\n {np.sum(M)}")

M =>
 [[-2  3]
 [ 4 -5]]
M > -10 =>
 [[ True  True]
 [ True  True]]
np.all(M > -10) => True
np.sum(M) =>
 0


<span class="label label-info"><i class="fa fa-info-circle" aria-hidden="true"></i> Truco</span> El operador `*` es la multiplicación elemento a elemento, para la multiplicación de matrices, se usa `@`.

In [122]:
print(f"M =>\n {M}")
print(f"M * M =>\n {M * M}")
print(f"M @ 2 =>\n {M @ M}")

M =>
 [[-2  3]
 [ 4 -5]]
M * M =>
 [[ 4  9]
 [16 25]]
M @ 2 =>
 [[ 16 -21]
 [-28  37]]


### Otros ejemplos

In [123]:
# Otras operaciones
# v1 = np.array([7, 9, 6])
# v2 = np.array([-1, -3, 0])

print(f"v2 * v2 => {v2 * v2}")
print(f"v2 @ v2 => {v2 @ v2}")
print(f"3 * v1 + v2 * v2 => {3 * v1 + v2 * v2}")
print(f"3 * v1 + v2 @ v2 => {3 * v1 + v2 @ v2}")

v2 * v2 => [1 9 0]
v2 @ v2 => 10
3 * v1 + v2 * v2 => [22 36 18]
3 * v1 + v2 @ v2 => [31 37 28]


In [124]:
# Otro ejemplo de vectores
v1 = np.array([[7, 9, 6]])
v2 = np.array([[-1, -3, 0]])
print(f"v1.shape => {v1.shape}")
print(f"v2 => {v2}")
print(f"v2.T => {v2.T}")
print(f"v2.shape => {v2.shape}")
print(f"v2.T.shape => {v2.T.shape}")
print(f"3 * v1 + v2 * v2 => {3 * v1 + v2 * v2}")
print(f"3 * v1 + v2 @ v2.T => {3 * v1 + v2 @ v2.T}")

v1.shape => (1, 3)
v2 => [[-1 -3  0]]
v2.T => [[-1]
 [-3]
 [ 0]]
v2.shape => (1, 3)
v2.T.shape => (3, 1)
3 * v1 + v2 * v2 => [[22 36 18]]
3 * v1 + v2 @ v2.T => [[31 37 28]]


<h1 class="jumbo">Ejercicios y retos   <a id="exercises"></a><a href="#index"><i class="fa fa-list-alt" aria-hidden="true"></i></a></h1>

### Ejercicio 1
Calcular los ceros de una parábola.

Dados los valores $a$, $b$, $c$ de un polinomio de segundo grado: $ax^2+bx+c$, encontrar los valores de $x$ para los que el polinomio se evalúa a cero: 
$$x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}$$

In [125]:
a = 2
b = 3
c = 5
 # ojo con las raíces de números negativos (aunque podrían usarse números complejos)
 ## AQUÍ EL CÓDIGO PARA CALCULAR LOS VALORES DE x 

### Ejercicio 2

Cómo utilizarías el acceso indexado a listas para obtener el valor 3 a partir de las siguiente listas?
```python
lista1 = [1, 2, 3, 4]
lista2 = [1, [2, [3, [4]]]]
lista3 = [[[[1], 2], 3], 4]
lista4 = [[1, 2],[[3], 4]]
lista5 = [[[1], [2], [3], [4]]]
lista6 = [[[[1]]], [[2]], [3], 4]
lista7 = [[[1], [[2, 3], 4]]]
```

In [126]:
lista1 = [1, 2, 3, 4]
# AQUÍ EL CÓDIGO PARA RECUPERAR EL VALOR 3

In [127]:
lista2 = [1, [2, [3, [4]]]]
# AQUÍ EL CÓDIGO PARA RECUPERAR EL VALOR 3

In [128]:
lista3 = [[[[1], 2], 3], 4]
# AQUÍ EL CÓDIGO PARA RECUPERAR EL VALOR 3

In [129]:
lista4 = [[1, 2],[[3], 4]]
# AQUÍ EL CÓDIGO PARA RECUPERAR EL VALOR 3

In [130]:
lista5 = [[[1], [2], [3], [4]]]
# AQUÍ EL CÓDIGO PARA RECUPERAR EL VALOR 3

In [131]:
lista6 = [[[[1]]], [[2]], [3], 4]
# AQUÍ EL CÓDIGO PARA RECUPERAR EL VALOR 3

In [132]:
lista7 = [[[1], [[2, 3], 4]]]
# AQUÍ EL CÓDIGO PARA RECUPERAR EL VALOR 3

### Ejercicio 3
Sumar dos vectores representados como listas. Si los vectores son $\vec{v_1}=(2,3)$ y $\vec{v_2}=(-3,1)$ el resultado sería $\vec{v_1}+\vec{v_2}=(-1,4)$

In [133]:
vec1 = [4, 8, 10]
vec2 = [1, 6, -2]
# AQUÍ EL CÓDIGO PARA CALCULAR vec1 + vec2

### Ejercicio 4 
Sumar dos vectores representados como arrays de numpy. Mirar la parte opcional de tensores

In [134]:
vec1 = np.array([4, 8, 10])
vec2 = np.array([1, 6, -2])
# AQUÍ EL CÓDIGO PARA CALCULAR vec1 + vec2

### Ejercicio 5
Calcular la norma de un vector representado como array de numpy.

Dado un vector $\vec{v}=(x_1, x_2, \ldots, x_n)$ calcular: 
$$\|x\|=\sqrt{\sum_{i=1}^n x_i^2}$$

Si el vector es $\vec{v}=(9,6,2)$, el resultado sería $11$

In [135]:
vec = np.array([5, 8, -3])
 # AQUÍ EL CÓDIGO PARA CALCULAR LA NORMA DE vec

### Ejercicio 6
Comprobar que un elemento pertenece a una lista. Si el elemento a buscar es 3 y la lista es <kbd>[4, 7, 9]</kbd>, el resultado sería <kbd>False</kbd>, en cambio para la lista <kbd>[4, 6, 3, 2]</kbd>, el resultado sería <kbd>True</kbd>.

<a class="label label-info" style="padding-top: .5em" type="button" data-toggle="collapse" data-target="#collapsePista00">
    <i class="fa fa-info-circle" aria-hidden="true"></i> Pista
</a>
  
<div class="collapse" id="collapsePista00">
  <div class="card card-body" style="-moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-right-colors: none; -moz-border-top-colors: none; background-color: #fefef1; border-bottom-right-radius: 12px; border-color: #f7a600; border-style: solid; border-width: 1px 1px 1px 5px; box-shadow: 2px 3px 5px #ccc; color: #222; display: table; line-height: 1.4em; margin: 10px 20px 20px; overflow: hidden; padding: 10px 16px;">
      El operador <kbd>in</kbd> puede utilizarse para comprobar que un elemento está dentro de una colección.
  </div>  
</div>

In [136]:
lista = [5, 8, 9, 10]
elto = 9
 # AQUÍ EL CÓDIGO

### Ejercicio 7
Comprobar que todos los elementos de una lista son iguales. Una lista como <kbd>[4, 4, 4]</kbd> daría <kbd>True</kbd>, una lista como <kbd>[1, 1, 1, 2]</kbd> daría <kbd>False</kbd>. 

<a class="label label-info" style="padding-top: .5em" type="button" data-toggle="collapse" data-target="#collapsePista01">
    <i class="fa fa-info-circle" aria-hidden="true"></i> Pista
</a>
  
<div class="collapse" id="collapsePista01">
  <div class="card card-body" style="-moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-right-colors: none; -moz-border-top-colors: none; background-color: #fefef1; border-bottom-right-radius: 12px; border-color: #f7a600; border-style: solid; border-width: 1px 1px 1px 5px; box-shadow: 2px 3px 5px #ccc; color: #222; display: table; line-height: 1.4em; margin: 10px 20px 20px; overflow: hidden; padding: 10px 16px;">
    Puedes utilizar la lista para crear un array de numpy y aprovecharte del broadcasting.
  </div>  
</div>

In [137]:
lista = [5, 5, 5, 5]
 # AQUÍ EL CÓDIGO

In [138]:
any([False, True])

True

### Ejercicio 8
Dada una secuencia de bases de una porción de ADN, representada como una cadena, calcular el [porcentaje GC](https://es.wikipedia.org/wiki/Contenido_GC).

<a class="label label-info" style="padding-top: .5em" type="button" data-toggle="collapse" data-target="#collapsePista02">
    <i class="fa fa-info-circle" aria-hidden="true"></i> Pista
</a>
  
<div class="collapse" id="collapsePista02">
  <div class="card card-body" style="-moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-right-colors: none; -moz-border-top-colors: none; background-color: #fefef1; border-bottom-right-radius: 12px; border-color: #f7a600; border-style: solid; border-width: 1px 1px 1px 5px; box-shadow: 2px 3px 5px #ccc; color: #222; display: table; line-height: 1.4em; margin: 10px 20px 20px; overflow: hidden; padding: 10px 16px;">
      Recuerda lo que hacía el método <kbd>count</kbd>, si no lo recuerdas, puedes usar <kbd>help(str.count)</kbd>.
  </div>  
</div>

In [139]:
adn = "AAGCATCGTGTCATGCATCG"
GC = '<Aquí el código solución>'

### Ejercicio 9
Comprobar que una número es capicúa, es decir, se lee lo mismo de izquierda a derecha que de derecha a izquierda. 

<a class="label label-info" style="padding-top: .5em" type="button" data-toggle="collapse" data-target="#collapsePista03">
    <i class="fa fa-info-circle" aria-hidden="true"></i> Pista
</a>
  
<div class="collapse" id="collapsePista03">
  <div class="card card-body" style="-moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-right-colors: none; -moz-border-top-colors: none; background-color: #fefef1; border-bottom-right-radius: 12px; border-color: #f7a600; border-style: solid; border-width: 1px 1px 1px 5px; box-shadow: 2px 3px 5px #ccc; color: #222; display: table; line-height: 1.4em; margin: 10px 20px 20px; overflow: hidden; padding: 10px 16px;">
      Utiliza el constructor de cadenas <kbd>str</kbd> para obtener una cadena a partir del número, y comprueba si la cadena obtenida es un palíndromo, es decir, es igual a su inversa.
        </div>  
</div>

In [140]:
valor = 6941496
# Aquí el código

### Ejercicio 10

Dada la siguiente estructura de datos:

In [141]:
datos = [{'v1': 'g1', 'v2': (3.1415, 2.7118, {'f': 'a/a=1'}) }, 
         {'v1': 'g2', 'v2': (-3.1415, -2.7118,  {'f': 'E=mc^2'}) }, 
         {'v1': 'g3', 'v2': (0, 1, {'f': 'e^{iπ}-1=0'}) },
        ]
datos

[{'v1': 'g1', 'v2': (3.1415, 2.7118, {'f': 'a/a=1'})},
 {'v1': 'g2', 'v2': (-3.1415, -2.7118, {'f': 'E=mc^2'})},
 {'v1': 'g3', 'v2': (0, 1, {'f': 'e^{iπ}-1=0'})}]

¿Cómo accederías al valor `'g1'`?

¿Cómo accederías al valor `3.1415`?

¿Cómo accederías al valor `-2.7118`?

¿Cómo accederías al valor `'e^{iπ}-1=0'`?

### Ejercicio 11

Dada la siguiente estructura de datos:

In [142]:
datos = {'xyz': ['g1', (3.1415, 2.7118,  {'f': 'a/a=1'})], 
         'abc': ['g2', (-3.1415, -2.7118, {'f': 'E=mc^2'})], 
         'X11': ['g3', (0, 1, {'f': 'e^{iπ}-1=0'})],
        }
datos

{'xyz': ['g1', (3.1415, 2.7118, {'f': 'a/a=1'})],
 'abc': ['g2', (-3.1415, -2.7118, {'f': 'E=mc^2'})],
 'X11': ['g3', (0, 1, {'f': 'e^{iπ}-1=0'})]}

¿Cómo accederías al valor `'g1'`?

¿Cómo accederías al valor `3.1415`?

¿Cómo accederías al valor `-2.7118`?

¿Cómo accederías al valor `'e^{iπ}-1=0'`?

###  Ejercicio 12 
Se tiene los siguientes datos de unos investigadores del área de lenguajes y sistemas informáticos:
- Nombre: Juan José Rodríguez, email: jjrodriguez@ubu.es, h-index: 22.
- Nombre: César Ignacio García Osorio, email: cgosorio@ubu.es, h-index: 14.
- Nombre: José Francisco Díez Pastor, email: jfdpastor@ubu.es, h-index: 8.
- Nombre: Álvar Arnáiz González, email: alvarag@ubu.es, h-index: 5.

Se quiere almacenar esta información con tres listas: `nombres`, `emails`, `h_indeces`, de forma que la información relacionada ocupe las mismas posiciones en cada lista. **Crea dichas listas**.

In [143]:
# Aquí la definición de las tres listas
nombres = [ ]
emails = [ ]
h_indeces = [ ]
# El acceso a los datos de un investigador consistiría en usar 
# el índice de su posición para recuperar los tres valores, si pos=0: nombre[pos], emails[pos], h_indices[pos]

###  Ejercicio 13 
Otra representación para los datos del ejercicio 10 sería tener una lista cuyos elementos sean tuplas con los tres valores que se quieren almacenar para cada investigador.  **Crea dicha lista**.

In [144]:
# Aquí la definición de la lista de tuplas
investigadores = [ ]
# El acceso a los datos de un investigador consistiría en usar 
# el índice de su posición para recuperar los tres valores, si pos=0: n, e, h = investigadores[pos]

###  Ejercicio 14 
Otra representación para los datos del ejercicio 10 sería tener una lista de diccionarios, en la que cada diccionario tenga las tres claves: `nombre`, `email`, `h_index`. **Crea dicha lista**.

In [145]:
# Aquí la definición de la lista de diccionarios
investigadores = [ ]
# El acceso a los datos de un investigador consistiría en usar 
# el índice de su posición para recuperar los tres valores, 
# si pos=0: inv=investigadores[pos], inv['nombre'], inv['email'], inv['h_index']

###  Ejercicio 15 
Otra representación para los datos del ejercicio 10 sería tener un diccionario indexado por el email, de forma que el valor asociado a cada clave sea una tupla con el nombre y el h-index. **Crea dicho diccionario**.

In [146]:
# Aquí la definición del diccionario de tuplas
investigadores = dict()
# El acceso a los datos de un investigador consistiría en usar 
# el índice de su posición para recuperar los tres valores, 
# si nombre, h_index = investigadores['cgosorio@ubu.es']

###  Ejercicio 16 
Se podrían combinar las representaciones del ejercicio 12 y 13 para tener un diccionario de diccionarios, en el que cada diccionario miembro este indexado por email, y cada uno de estos diccionarios tenga tres claves (incluida de nuevo la del email). **Crea dicho diccionario**.

In [147]:
# Aquí la definición del diccionario de diccionarios
investigadores = dict()
# El acceso a los datos de un investigador consistiría en usar 
# el índice de su posición para recuperar los tres valores, 
# si nombre, inv = investigadores['cgosorio@ubu.es'], inv['nombre'], inv['email'], inv['h_index']

<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> Como ha podido verse, la misma situación puede representarse de varias formas distintas. **Que una representación sea más adecuada que otra dependerá del problema concreto que quiera resolverse**.  
</div>


<div class="alert alert-info">
   <i style="font-size: larger;" class="fa fa-info-circle" aria-hidden="true"></i> En esta sesión se han visto las estructuras de datos básicas de Python (se han incluido los arrays de numpy, porque aunque no es un tipo básico del lenguaje, en un contexto científico vamos a estar utilizando el `import numpy as np` prácticamente por sistema). En la siguiente sesión se verán las estructuras de control que permite la manipulación de los datos. Y por último, en la sesión 3 se verán estructuras de datos incluso más potentes, y algunas de las bibliotecas más interesantes en el contexto de la investigación y el análisis de datos.  
</div>
